"""empty message

Revision ID: dd0f3c3494b8
Revises: 
Create Date: 2021-06-03 17:09:55.436144

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'dd0f3c3494b8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('userok',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.String(length=88), nullable=True),
    sa.Column('age', sa.String(length=44), nullable=True),
    sa.Column('addr', sa.String(length=88), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('user')
    op.drop_table('tsuser')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tsuser',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('username', mysql.VARCHAR(collation='utf8_unicode_ci', length=40), nullable=True),
    sa.Column('addr', mysql.VARCHAR(collation='utf8_unicode_ci', length=40), nullable=True),
    sa.Column('bank', mysql.VARCHAR(collation='utf8_unicode_ci', length=40), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_unicode_ci',
    mysql_default_charset='utf8',
    mysql_engine='MyISAM'
    )
    op.create_table('user',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('username', mysql.VARCHAR(collation='utf8_unicode_ci', length=50), nullable=True),
    sa.Column('passwd', mysql.VARCHAR(collation='utf8_unicode_ci', length=66), nullable=True),
    sa.Column('phone', mysql.VARCHAR(collation='utf8_unicode_ci', length=88), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_unicode_ci',
    mysql_default_charset='utf8',
    mysql_engine='MyISAM'
    )
    op.drop_table('userok')
    # ### end Alembic commands ###
